server:
  port: 8091
spring:
  data:
    mongodb:
      # no authetication in local
      # username:
      # password:
      # authentication-database: admin
      host: localhost
      port: 27017
      database: customer
 
zipkin:
  baseUrl: http://localhost:9411    