server:
  port: 8090
spring:
  data:
    mongodb:
      # no authetication in local
      # username:
      # password:
      # authentication-database: admin
      host: localhost
      port: 27017
      database: customer
      