server:
  port: 8222
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer-service
          uri: lb:http://CUSTOMER-SERVICE
          predicates:
            - Path=/api/v1/customers/**
        - id: student-onboarding-service
          uri: lb:http://STUDENT-ONBOARDING-SERVICE
          predicates:
            - Path=/api/v1/students/**
            
            
zipkin:
  baseUrl: http://localhost:9411
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
